### ISSUE TITLE
Current REPL doesn't print parsed results nor errors

### ISSUE THREAD

**Issue by ahirner** [platzhaltr/datr.scala#2]
This is due to the return type of [SimpleInterface.read](https://github.com/platzhaltr/datr.scala/blob/master/src/main/scala/org/platzhaltr/SimpleInterface.scala#L11) being `Unit`.
Changing it to `String` solved this issue on current master.

**Comment by oschrenk** [comment]
Thanks! Will fix it when I have access to a proper coding env, which might take a while as I'm on a long vacation.

**Comment by oschrenk** [comment]
Done. Thanks.
